"""added address table

Revision ID: 03d6851d9060
Revises: 0ff34125ef18
Create Date: 2022-01-10 23:36:06.042682

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '03d6851d9060'
down_revision = '0ff34125ef18'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('address',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('street', sa.String(length=128), nullable=True),
    sa.Column('house', sa.String(length=10), nullable=True),
    sa.Column('building', sa.String(length=50), nullable=True),
    sa.Column('entrance', sa.String(length=3), nullable=True),
    sa.Column('floor', sa.String(length=3), nullable=True),
    sa.Column('apartment', sa.String(length=5), nullable=True),
    sa.Column('additional_info', sa.String(length=128), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('address')
    # ### end Alembic commands ###
