"""added sex and phone col in user table

Revision ID: 0ad31af31865
Revises: 22614e8f0b06
Create Date: 2022-01-02 14:26:54.382609

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0ad31af31865'
down_revision = '22614e8f0b06'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('sex', sa.String(length=7), nullable=True))
    op.add_column('user', sa.Column('phone_number', sa.String(length=11), nullable=True))
    op.create_index(op.f('ix_user_phone_number'), 'user', ['phone_number'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_phone_number'), table_name='user')
    op.drop_column('user', 'phone_number')
    op.drop_column('user', 'sex')
    # ### end Alembic commands ###
