"""added subcategory table

Revision ID: 4c345c242ba9
Revises: ee064a84db2f
Create Date: 2022-01-14 01:29:58.348109

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4c345c242ba9'
down_revision = 'ee064a84db2f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('subcategory',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name_subcategory', sa.String(length=30), nullable=True),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['menu_category.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.alter_column('food', 'slug',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.create_unique_constraint(None, 'food', ['slug'])
    op.alter_column('menu_category', 'slug',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.create_unique_constraint(None, 'menu_category', ['slug'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'menu_category', type_='unique')
    op.alter_column('menu_category', 'slug',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.drop_constraint(None, 'food', type_='unique')
    op.alter_column('food', 'slug',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.drop_table('subcategory')
    # ### end Alembic commands ###
