"""user_food(favourite) table

Revision ID: 9d022e68dd92
Revises: 4c345c242ba9
Create Date: 2022-01-14 20:14:21.782376

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9d022e68dd92'
down_revision = '4c345c242ba9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_food',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('food_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['food_id'], ['food.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'food_id')
    )
    op.drop_table('subcategory')
    op.alter_column('food', 'slug',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.create_unique_constraint(None, 'food', ['slug'])
    op.alter_column('menu_category', 'slug',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.create_unique_constraint(None, 'menu_category', ['slug'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'menu_category', type_='unique')
    op.alter_column('menu_category', 'slug',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.drop_constraint(None, 'food', type_='unique')
    op.alter_column('food', 'slug',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.create_table('subcategory',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name_subcategory', sa.VARCHAR(length=30), nullable=True),
    sa.Column('category_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['menu_category.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('user_food')
    # ### end Alembic commands ###
