"""order_food table

Revision ID: ac294e6c7e45
Revises: 1e61df1aa455
Create Date: 2022-02-03 10:49:20.418857

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ac294e6c7e45'
down_revision = '1e61df1aa455'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('order_food',
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('food_id', sa.Integer(), nullable=False),
    sa.Column('food_quantity', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['food_id'], ['food.id'], ),
    sa.ForeignKeyConstraint(['order_id'], ['order.id'], ),
    sa.PrimaryKeyConstraint('order_id', 'food_id')
    )
    with op.batch_alter_table('food', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['slug'])

    with op.batch_alter_table('menu_category', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['slug'])

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_phone_number'), ['phone_number'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_phone_number'))

    with op.batch_alter_table('menu_category', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    with op.batch_alter_table('food', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    op.drop_table('order_food')
    # ### end Alembic commands ###
