"""update menu_category table path column

Revision ID: cadd978a2f72
Revises: b2ed170ea3f3
Create Date: 2022-01-03 17:36:09.066286

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cadd978a2f72'
down_revision = 'b2ed170ea3f3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('menu_category', sa.Column('path', sa.Unicode(length=128), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('menu_category', 'path')
    # ### end Alembic commands ###
