"""reg date col

Revision ID: e03c2c075619
Revises: 9d022e68dd92
Create Date: 2022-01-24 10:56:12.750953

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e03c2c075619'
down_revision = '9d022e68dd92'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'food', ['slug'])
    op.create_unique_constraint(None, 'menu_category', ['slug'])
    op.drop_index('ix_user_phone_number', table_name='user')
    op.create_index(op.f('ix_user_phone_number'), 'user', ['phone_number'], unique=True)
    op.create_index(op.f('ix_user_registration_date'), 'user', ['registration_date'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_registration_date'), table_name='user')
    op.drop_index(op.f('ix_user_phone_number'), table_name='user')
    op.create_index('ix_user_phone_number', 'user', ['phone_number'], unique=False)
    op.drop_constraint(None, 'menu_category', type_='unique')
    op.drop_constraint(None, 'food', type_='unique')
    # ### end Alembic commands ###
