"""added slug col in food table

Revision ID: ee064a84db2f
Revises: 03d6851d9060
Create Date: 2022-01-13 16:20:48.134206

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ee064a84db2f'
down_revision = '03d6851d9060'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('food', sa.Column('slug', sa.String(length=255), nullable=True))
    op.create_unique_constraint(None, 'food', ['slug'])
    op.create_unique_constraint(None, 'menu_category', ['slug'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'menu_category', type_='unique')
    op.drop_constraint(None, 'food', type_='unique')
    op.drop_column('food', 'slug')
    # ### end Alembic commands ###
