"""added slug col in menu_category table

Revision ID: f29581305070
Revises: cadd978a2f72
Create Date: 2022-01-04 17:42:02.364481

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f29581305070'
down_revision = 'cadd978a2f72'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('menu_category', sa.Column('slug', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('menu_category', 'slug')
    # ### end Alembic commands ###
